# GitHub Sponsors
github: [a2w-A, algo2world]

# Custom enterprise & community sponsorship links
custom:
  - https://algo2world.com#commercial-support
  - https://a2w.in/network-sponsorship

# Community Platforms
patreon: algo2world
ko_fi: algo2world
buy_me_a_coffee: algo2world
