import React, { useState } from "react";
import { ShieldCheck, AlertTriangle, CheckCircle2, XCircle, Terminal, Copy, Check, FileCode, Shield, RefreshCw } from "lucide-react";
import { SecurityCheck, ProxmoxConnectionStatus } from "../types";
import { NotConnectedBanner } from "./NotConnectedBanner";

interface SecurityAuditorViewProps {
  checks: SecurityCheck[];
  connectionStatus: ProxmoxConnectionStatus | null;
  onRefresh: () => void;
  onConfigureClick: () => void;
}

export function SecurityAuditorView({
  checks,
  connectionStatus,
  onRefresh,
  onConfigureClick,
}: SecurityAuditorViewProps) {
  const [copiedScript, setCopiedScript] = useState(false);
  const [showScriptModal, setShowScriptModal] = useState(false);

  const isConnected = connectionStatus?.connected === true;

  if (!isConnected) {
    return (
      <NotConnectedBanner
        onConfigureClick={onConfigureClick}
        error={connectionStatus?.lastError}
      />
    );
  }

  const passedCount = checks.filter((c) => c.status === "PASS").length;
  const warnCount = checks.filter((c) => c.status === "WARN").length;
  const failCount = checks.filter((c) => c.status === "FAIL").length;
  const score = checks.length
    ? Math.round(((passedCount * 1.0 + warnCount * 0.5) / checks.length) * 100)
    : 100;

  const nodeName = connectionStatus.nodeName || "pve";

  const remediationScript = `#!/usr/bin/env bash
# ==============================================================================
# Proxmox VE Automated Security Hardening & Remediation Script
# Generated by proxmox-pve-toolkit for node: ${nodeName}
# Algo2World Enterprise Systems • https://algo2world.com
# ==============================================================================
set -euo pipefail

echo '>>> [1/4] Enforcing Proxmox Firewall at Cluster & Node Levels...'
pve-firewall start || true
pvesh set /cluster/firewall/options -enable 1 || true
pvesh set /nodes/${nodeName}/firewall/options -enable 1 || true

echo '>>> [2/4] Hardening Host SSH Daemon Configuration...'
sed -i 's/^#*PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config || true
sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config || true
systemctl restart sshd || true

echo '>>> [3/4] Provisioning Dedicated Automation Service Account with Scoped ACL...'
pveum role add PVEToolkitRole -privs "VM.Audit VM.Backup VM.PowerMgmt Sys.Audit" || true
pveum user add devops@pve --comment "DevOps Automation Service Account" || true
pveum acl modify / -user devops@pve -role PVEToolkitRole || true

echo '>>> [4/4] Security Baseline Hardening Complete!'
`;

  const copyScript = () => {
    navigator.clipboard.writeText(remediationScript);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Score & Summary Bento Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="flex items-center space-x-4">
            <div className="w-16 h-16 rounded-2xl bg-emerald-950/40 border border-emerald-800/40 flex flex-col items-center justify-center text-emerald-400 shrink-0">
              <span className="text-2xl font-bold font-mono">{score}%</span>
              <span className="text-[10px] font-mono font-bold text-emerald-300">SCORE</span>
            </div>
            <div>
              <h2 className="text-lg font-bold text-white flex items-center space-x-2">
                <ShieldCheck className="w-5 h-5 text-emerald-400" />
                <span>Hypervisor Security Hardening Baseline</span>
              </h2>
              <p className="text-xs text-slate-400 mt-1 font-mono">
                Auditing Proxmox cluster firewall, 2FA, token privilege separation, API restrictions, and SSL.
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <div className="flex items-center space-x-2 text-xs font-mono font-semibold">
              <span className="px-2.5 py-1 bg-emerald-950/50 text-emerald-400 border border-emerald-800/40 rounded-lg">
                {passedCount} PASS
              </span>
              <span className="px-2.5 py-1 bg-amber-950/50 text-amber-400 border border-amber-800/40 rounded-lg">
                {warnCount} WARN
              </span>
              <span className="px-2.5 py-1 bg-rose-950/50 text-rose-400 border border-rose-800/40 rounded-lg">
                {failCount} FAIL
              </span>
            </div>

            <button
              onClick={onRefresh}
              className="p-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 border border-slate-700 transition"
              title="Re-run Security Audit"
            >
              <RefreshCw className="w-4 h-4" />
            </button>

            <button
              onClick={() => setShowScriptModal(true)}
              className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-mono font-semibold rounded-xl flex items-center space-x-1.5 shadow-md shadow-indigo-600/20 transition"
            >
              <FileCode className="w-3.5 h-3.5" />
              <span>VIEW FIX SCRIPT</span>
            </button>
          </div>
        </div>
      </div>

      {/* Compliance Table */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-xl">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-300 font-mono">
            <thead className="bg-slate-950 text-slate-400 uppercase font-semibold text-[11px] font-sans border-b border-slate-800">
              <tr>
                <th className="px-6 py-3 font-mono">Check ID</th>
                <th className="px-4 py-3">Category</th>
                <th className="px-4 py-3">Security Check Title</th>
                <th className="px-4 py-3 text-center">Status</th>
                <th className="px-4 py-3 text-center">Severity</th>
                <th className="px-4 py-3 font-sans">Findings & Recommended Remediation</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60 text-[11px]">
              {checks.map((c) => (
                <tr key={c.id} className="hover:bg-slate-850 transition">
                  <td className="px-6 py-3.5 font-bold text-slate-400">{c.id}</td>
                  <td className="px-4 py-3.5 text-slate-300 font-sans">{c.category}</td>
                  <td className="px-4 py-3.5 font-sans font-semibold text-white">{c.title}</td>
                  <td className="px-4 py-3.5 text-center">
                    <span
                      className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold inline-flex items-center space-x-1 ${
                        c.status === "PASS"
                          ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20"
                          : c.status === "WARN"
                          ? "bg-amber-500/10 text-amber-300 border border-amber-500/20"
                          : "bg-rose-500/10 text-rose-400 border border-rose-500/20"
                      }`}
                    >
                      {c.status === "PASS" ? (
                        <CheckCircle2 className="w-3 h-3 inline" />
                      ) : (
                        <AlertTriangle className="w-3 h-3 inline" />
                      )}
                      <span>{c.status}</span>
                    </span>
                  </td>
                  <td className="px-4 py-3.5 text-center">
                    <span
                      className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                        c.severity === "CRITICAL"
                          ? "bg-rose-950 text-rose-300 border border-rose-800"
                          : c.severity === "HIGH"
                          ? "bg-amber-950 text-amber-300 border border-amber-800"
                          : "bg-slate-800 text-slate-300"
                      }`}
                    >
                      {c.severity}
                    </span>
                  </td>
                  <td className="px-4 py-3.5 text-slate-300 font-sans text-xs">
                    <p className="text-slate-300">{c.details}</p>
                    {c.status !== "PASS" && (
                      <p className="text-indigo-400 font-mono text-[11px] mt-1 bg-slate-950 p-2 rounded-lg border border-slate-800">
                        Fix: {c.remediation}
                      </p>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Script Modal */}
      {showScriptModal && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4">
          <div className="bg-slate-900 border border-slate-800 rounded-2xl max-w-2xl w-full overflow-hidden shadow-2xl">
            <div className="px-6 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-950">
              <div className="flex items-center space-x-2 text-white font-bold text-sm">
                <Terminal className="w-4 h-4 text-indigo-400" />
                <span>Generated Remediation Script (fix_hardening.sh)</span>
              </div>
              <button
                onClick={() => setShowScriptModal(false)}
                className="text-slate-400 hover:text-white text-xs p-1"
              >
                ✕
              </button>
            </div>

            <div className="p-5">
              <pre className="bg-black text-emerald-400 font-mono text-xs p-4 rounded-xl overflow-x-auto max-h-80 border border-slate-800">
                {remediationScript}
              </pre>

              <div className="mt-4 flex items-center justify-between">
                <span className="text-xs text-slate-400 font-mono">
                  Run directly on Proxmox node as root: <code className="text-indigo-400 font-bold">bash fix_hardening.sh</code>
                </span>
                <button
                  onClick={copyScript}
                  className="px-3.5 py-1.5 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-mono font-semibold rounded-lg flex items-center space-x-1.5 transition"
                >
                  {copiedScript ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copiedScript ? "COPIED" : "COPY BASH SCRIPT"}</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
